version: '3.8'

services:
  pterodactyl-bot:
    build: .
    container_name: pterodactyl-whatsapp-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
    env_file:
      - .env
    volumes:
      - ./sessions:/app/sessions
      - ./logs:/app/logs
    networks:
      - bot-network
    ports:
      - "3000:3000"  # Jika ada webhook
    depends_on:
      - redis
      - database
    
  redis:
    image: redis:7-alpine
    container_name: pterodactyl-bot-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - bot-network

  database:
    image: postgres:15-alpine
    container_name: pterodactyl-bot-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: pterodactyl_bot
      POSTGRES_USER: bot_user
      POSTGRES_PASSWORD: secure_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bot-network

volumes:
  redis-data:
  postgres-data:

networks:
  bot-network:
    driver: bridge